# Generated by Django 3.2.6 on 2021-09-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbangreen', '0002_rename_new_arrivals_ug_new_arrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ug_best_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('hot', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ug_new_arrivals',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
